### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by syaifulnizamyahya** [Azure/azure-webjobs-sdk-samples#11]
Downloaded the sample. Compile. Doesnt work.

**Comment by MatthewSteeples** [comment]
Not sure whether you're after a resolution to your problem, but if you are I'd suggest including some more information such as

- What "doesn't work"
- What (if any) errors are showing
- What version of Visual Studio you're using

**Comment by syaifulnizamyahya** [comment]
Try downloading the sample. Rebuild all. See if that works. Doesn't work on my end. Im using Visual Studio 2017. I already removed the source.

**Comment by syaifulnizamyahya** [comment]
My bad. I did not configure the App.config. Once properly configured, everything works fine.

I had 1 suggestion. It would be nice if anyone can download and run without having to configure anything. Maybe using emulator endpoints or the like. 

:+1:
